import { CalendarRange, Check, Eye, EyeOff, Sparkles } from 'lucide-react'
import { useState } from 'react'
import { Link, useNavigate } from 'react-router'

export function AuthPage({ initialMode = 'login' }: { initialMode?: 'login' | 'create' }) {
  const [mode, setMode] = useState(initialMode)
  const [showPassword, setShowPassword] = useState(false)
  const navigate = useNavigate()
  const creating = mode === 'create'
  function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); localStorage.setItem('smart-timetable-user', 'Tanu'); navigate('/') }
  return <main className="grid min-h-screen bg-canvas lg:grid-cols-[1.05fr_.95fr]">
    <section className="relative hidden overflow-hidden bg-[#171a4d] p-12 text-white lg:flex lg:flex-col"><div className="absolute -left-24 top-16 size-80 rounded-full bg-cyan-400/20 blur-3xl" /><div className="absolute -bottom-24 right-0 size-96 rounded-full bg-violet-500/30 blur-3xl" /><Link to="/" className="relative flex items-center gap-3 text-white"><span className="grid size-11 place-items-center rounded-xl bg-white/15"><CalendarRange size={23} /></span><span className="text-lg font-extrabold">SmartTimetable</span></Link><div className="relative my-auto max-w-lg"><span className="inline-flex items-center gap-2 rounded-full border border-white/20 bg-white/10 px-3 py-1.5 text-xs font-bold"><Sparkles size={14} /> BUILT FOR TEACHERS</span><h1 className="mt-6 text-4xl font-extrabold leading-tight">Plan a week of classes in minutes, not hours.</h1><p className="mt-5 text-base leading-7 text-indigo-100">Add your subjects, departments, teachers, and rooms. Our scheduling assistant prepares a conflict-aware weekly timetable your team can review.</p><ul className="mt-9 space-y-4 text-sm font-semibold text-indigo-50">{['One place for every department and subject', 'Assign several teachers to the same subject', 'Generate a clear weekly timetable draft'].map((item) => <li key={item} className="flex gap-3"><span className="grid size-5 shrink-0 place-items-center rounded-full bg-cyan-300 text-[#171a4d]"><Check size={13} strokeWidth={3} /></span>{item}</li>)}</ul></div><p className="relative text-xs text-indigo-200">A calmer way to run your academic schedule.</p></section>
    <section className="flex items-center justify-center px-5 py-10 sm:p-10"><div className="w-full max-w-md"><Link to="/" className="mb-10 flex items-center gap-2 text-ink lg:hidden"><span className="grid size-9 place-items-center rounded-xl bg-brand text-white"><CalendarRange size={19} /></span><span className="font-extrabold">SmartTimetable</span></Link><p className="text-sm font-bold text-brand">{creating ? 'GET STARTED FREE' : 'WELCOME BACK'}</p><h2 className="mt-2 text-3xl font-extrabold tracking-tight">{creating ? 'Create your workspace' : 'Sign in to your workspace'}</h2><p className="mt-2 text-sm leading-6 text-ink-muted">{creating ? 'Set up your institution and start planning your timetable.' : 'Manage your departments and schedules in one calm place.'}</p><form onSubmit={submit} className="mt-8 space-y-4">{creating && <label className="block text-sm font-bold">Your name<input required placeholder="e.g. Priya Sharma" className="mt-2 w-full rounded-xl border bg-surface px-4 py-3 outline-none transition focus:border-brand focus:ring-4 focus:ring-brand/10" /></label>}{creating && <label className="block text-sm font-bold">Institution name<input required placeholder="e.g. Greenfield College" className="mt-2 w-full rounded-xl border bg-surface px-4 py-3 outline-none transition focus:border-brand focus:ring-4 focus:ring-brand/10" /></label>}<label className="block text-sm font-bold">Work email<input required type="email" placeholder="you@college.edu" className="mt-2 w-full rounded-xl border bg-surface px-4 py-3 outline-none transition focus:border-brand focus:ring-4 focus:ring-brand/10" /></label><label className="block text-sm font-bold">Password<span className="relative mt-2 block"><input required minLength={8} type={showPassword ? 'text' : 'password'} placeholder="At least 8 characters" className="w-full rounded-xl border bg-surface px-4 py-3 pr-12 outline-none transition focus:border-brand focus:ring-4 focus:ring-brand/10" /><button type="button" onClick={() => setShowPassword(!showPassword)} className="absolute right-3 top-3 text-ink-muted" aria-label="Show password">{showPassword ? <EyeOff size={19} /> : <Eye size={19} />}</button></span></label>{!creating && <div className="text-right"><button type="button" className="text-sm font-bold text-brand">Forgot password?</button></div>}<button className="w-full rounded-xl bg-brand px-4 py-3.5 text-sm font-extrabold text-white shadow-[0_12px_24px_rgb(91_92_240_/_.25)] transition hover:bg-brand-strong" type="submit">{creating ? 'Create workspace' : 'Sign in'} <span aria-hidden="true">→</span></button></form><p className="mt-7 text-center text-sm text-ink-muted">{creating ? 'Already have an account?' : 'New to SmartTimetable?'} <button onClick={() => setMode(creating ? 'login' : 'create')} className="font-extrabold text-brand">{creating ? 'Sign in' : 'Create an account'}</button></p></div></section>
  </main>
}
